apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-gke-deployment
spec:
  replicas: 2 # Run two instances of our application
  selector:
    matchLabels:
      app: hello-gke
  template:
    metadata:
      labels:
        app: hello-gke
    spec:
      containers:
      - name: hello-app-container
        # IMPORTANT: You will replace this with your own image path
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080
